"""Migrate images to URLs

Revision ID: 3342137f4525
Revises: 1ed9d72593f7
Create Date: 2026-05-17 19:46:24.271069

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3342137f4525'
down_revision = '1ed9d72593f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memories-images')
    op.drop_table('user-images')
    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_image_url')

    with op.batch_alter_table('memories', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    op.create_table('user-images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user-images_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user-images_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user-images_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('user_id', name=op.f('user-images_user_id_key1'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('memories-images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('memorie_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['memorie_id'], ['memories.id'], name=op.f('memories-images_memorie_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('memories-images_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('memories-images_pkey')),
    sa.UniqueConstraint('memorie_id', name=op.f('memories-images_memorie_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
