"""add memorie id and rename

Revision ID: 6eabdfd4fccd
Revises: d99ac92dc21d
Create Date: 2025-09-16 23:15:54.465852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6eabdfd4fccd'
down_revision = 'd99ac92dc21d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users-images')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users-images',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('img', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('mimetype', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('users-images_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('users-images_pkey'))
    )
    # ### end Alembic commands ###
